---
- name: Install flatpak
  ansible.builtin.package:
    name:
      - flatpak
      - gnome-software-plugin-flatpak
    state: present

- name: Ensure Flathub remote is added
  community.general.flatpak_remote:
    name: flathub
    state: present
    url: https://flathub.org/repo/flathub.flatpakrepo
