---
- name: Create systemd service file to add VIP from template
  ansible.builtin.template:
    src: add-vip.service.j2
    dest: /etc/systemd/system/add-vip.service
    mode: "0600"
  notify: Reload systemd
