---
- name: Get current NFS shares
  ansible.builtin.command: midclt call sharing.nfs.query
  register: sharing_nfs_query
  changed_when: false

- name: Ensure NFS shares exist
  ansible.builtin.command: >
    midclt call sharing.nfs.create '{{ item | to_json }}'
  loop: "{{ shares.nfs }}"
  changed_when: false
  when: >
    (sharing_nfs_query.stdout | from_json | selectattr('path', 'equalto', item.path) | list | length) == 0
  register: sharing_nfs_create
