---
- name: Include NFS share creation for each server
  ansible.builtin.include_tasks: create-nfs-shares.yaml

- name: Include iSCSI extents creation for each server
  ansible.builtin.include_tasks: create-iscsi-shares.yaml

