---
- name: Get existing iSCSI extents from {{ truenas_instance.host }}
  ansible.builtin.uri:
    url: "{{ truenas_instance.host }}/api/v2.0/iscsi/extent/"
    method: GET
    headers:
      Authorization: "Bearer {{ truenas_instance.api_key }}"
      Content-Type: "application/json"
    return_content: true
    validate_certs: false
  register: iscsi_extents

- name: Debug existing shares
  ansible.builtin.debug:
    msg: "{{ iscsi_extents.json }}"

- name: Create iSCSI extents that are missing
  ansible.builtin.uri:
    url: "https://truenas-b.lan.stamx.nl/api/v2.0/iscsi/extent/"
    method: POST
    headers:
      Authorization: "Bearer {{ truenas.b.api_key }}"
      Content-Type: "application/json"
    body_format: json
    body: "{{ item }}"
    status_code: [200, 201]
    validate_certs: false
  loop: "{{ iscsi_extends }}"
  when: >
    not iscsi_extents.json | selectattr('name', '==', item.name) | list
