---
- name: Get current NFS shares from {{ truenas_instance.host }}
  ansible.builtin.uri:
    url: "{{ truenas_instance.host }}/api/v2.0/sharing/nfs/"
    method: GET
    headers:
      Authorization: "Bearer {{ truenas_instance.api_key }}"
      Content-Type: "application/json"
    return_content: true
    validate_certs: false
  register: current_nfs

- name: Create NFS shares that are missing
  ansible.builtin.uri:
    url: "{{ truenas_instance.host }}/api/v2.0/sharing/nfs/"
    method: POST
    headers:
      Authorization: "Bearer {{ truenas_instance.api_key }}"
      Content-Type: "application/json"
    body_format: json
    body: "{{ item }}"
    status_code: [200, 201]
    validate_certs: false
  loop: "{{ nfs_shares }}"
  when: >
    not current_nfs.json | selectattr('path', '==', item.path) | list
