---
- ansible.builtin.include_tasks: "api-facts.yaml"

- ansible.builtin.include_tasks: "get-all-snapshot-tasks.yaml"

- name: Disable existing snapshot tasks on truenas-master
  uri:
    url: "{{ truenas_api_baseurl }}/pool/snapshottask/id/{{ item }}"
    method: PUT
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
      Content-Type: "application/json"
    validate_certs: no
    body_format: json
    body:
      enabled: "{{ enabled }}"
  register: disable_existing_snapshot_result
  loop: "{{ existing_snapshot_result.json | map(attribute='id') | list }}"
