---
- ansible.builtin.include_tasks: "api-facts.yaml"

- name: Get all existing replication tasks on truenas-master
  uri:
    url: "{{ truenas_api_baseurl }}/replication"
    method: GET
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
      Content-Type: "application/json"
    validate_certs: no
  register: existing_replication_result
