---
- name: Query snapshot tasks
  ansible.builtin.include_tasks: get-pool-snapshot-tasks.yaml

- name: Run existing snapshot tasks
  ansible.builtin.include_tasks: run-pool-snapshot-tasks.yaml
  vars:
    id: "{{ pool_snapshottask_query.stdout | from_json | map(attribute='id') | list }}"

- name: Query replication tasks
  ansible.builtin.include_tasks: get-replication-tasks.yaml

- name: Wait for replication tasks to complete
  ansible.builtin.include_tasks: wait-for-replication-tasks.yaml
