- name: Create non-root user for ansible
  hosts: localhost
  become_user: coen
  gather_facts: false
  vars:
    user_name: "ansible"
    user_sudo: true

  tasks:
    - name: Install sudo
      ansible.builtin.import_role:
        name: sudo
      become: true

    - name: Create ansible user
      ansible.builtin.import_role:
        name: user
      become: true

    - name: Add ansible public authorized ssh key
      ansible.builtin.import_role:
        name: ansible-ssh-authorized-key
      become: true
