- name: Create non-root user for ansible
  hosts: k3s_cluster
  become: true
  become_user: root
  gather_facts: false
  vars:
    user_name: "ansible"
    user_sudo: true

  tasks:
    - name: Install sudo
      ansible.builtin.import_role:
        name: sudo

    - name: Create ansible user
      ansible.builtin.import_role:
        name: user

    - name: Add ansible public authorized ssh key
      ansible.builtin.import_role:
        name: ansible-ssh-authorized-key
