---
- name: K3s system maintenance
  hosts: k3s_cluster
  become: true
  serial: 1
  any_errors_fatal: true
  tasks:
    - name: Start rolling-update
      ansible.builtin.include_role:
        name: k3s
        tasks_from: rolling-update
