---
- name: Play for installing a clean bare K3s cluster without any deployments
  hosts: k3s_cluster
  gather_facts: true
  become: true
  roles:
    - common
  tasks:
    - name: Include bare task
      ansible.builtin.include_role:
        name: k3s
        tasks_from: bare.yaml
