---
- name: Play for preparing storage nodes for longhorn
  hosts: k3s_storage
  gather_facts: true
  become: true
  tasks:
    - name: Start prepare longhorn
      ansible.builtin.include_role:
        name: k3s
        tasks_from: prepare-longhorn
