---
- name: "Play for localhost"
  hosts: localhost
  connection: local
  become: true
  tasks:
    - name: Update apt repo and cache on
      ansible.builtin.apt:
        update_cache: true
        cache_valid_time: 3600
        upgrade: dist

    - name: Install python packages
      ansible.builtin.pip:
        name:
          - passlib
          - netaddr

    - name: Install apt packages
      ansible.builtin.apt:
        pkg:
          - pinta
          - curl
          - code
          - git
          - brave-browser
          - python3
          - vlc
        autoclean: true
        autoremove: true
