- name: Create non-root ansible user for ansible
  hosts: k3s_cluster, proxmox
  become: true
  become_user: root
  remote_user: root
  gather_facts: true
  vars:
    user_name: "coen"
    user_sudo: true
    add_ansible_ssh_public_key: true

  tasks:
    - name: Install sudo
      ansible.builtin.import_role:
        name: sudo
      become: true

    - name: Create ansible user
      ansible.builtin.import_role:
        name: user
      become: true
