---
- name: Proxmox system maintenance
  hosts: proxmox
  become: true
  serial: 1
  any_errors_fatal: true
  tasks:
    - name: Start rolling-update
      ansible.builtin.include_role:
        name: proxmox
        tasks_from: rolling-update
