---
- name: Play to backup files te external hdd attached to a Proxmox host
  hosts: pve-a
  gather_facts: true
  become: true
  become_user: root
  vars:
    backup_disk_label: "BACKUP"

  tasks:
    - name: Create a mountpoint directory if it does not exist
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        mode: "0755"
      loop:
        - "/mnt/external"
        - "/mnt/storage-server"

    - name: Mount external disk
      ansible.posix.mount:
        path: "/mnt/external"
        src: LABEL="{{ backup_disk_label }}"
        state: mounted
        fstype: ext4

    - name: Mount Storage-server NFS volume
      ansible.posix.mount:
        src: storage-server-lagg.lan.theautomation.nl:/mnt/r10_8tb/downloads
        path: "/mnt/storage-server"
        opts: rw,sync,hard
        state: mounted
        fstype: nfs


    # - name: Unmount a mounted volume
    #   ansible.posix.mount:
    #     path: /mnt/external
    #     state: unmounted
