---
- name: "Play to change the truenas Master"
  hosts: localhost
  connection: local
  gather_facts: true
  vars:
    domain: "lan.theautomation.nl"
    truenas_hosts:
      - name: "master"
      - name: "a"
      - name: "b"
    truenas_ssh_credentials_id:
      a: 4
      b: 4
    truenas_ssh_private_key_id:
      a:
      b: 3

  tasks:
    - name: Flush DNS cache
      ansible.builtin.command: resolvectl flush-caches
      when: ansible_distribution in ['Ubuntu', 'Debian', 'Fedora']

    - name: Set TrueNAS API variables
      include_vars: "group_vars/truenas/{{ item }}.yaml"
      loop:
        - vars
        - vault

    - name: Query DNS for the IP addresses
      command: "dig +short truenas-{{ item.name }}.{{ domain }}"
      loop: "{{ truenas_hosts }}"
      register: dig_results

    - name: Set IP address variables
      set_fact:
        "truenas_{{ item.item.name }}_ip": "{{ item.stdout_lines[0] }}"
      loop: "{{ dig_results.results }}"

    - name: Display the IP address variables
      debug:
        msg:
          - "truenas_master_ip: {{ truenas_master_ip }}"
          - "truenas_a_ip: {{ truenas_a_ip }}"
          - "truenas_b_ip: {{ truenas_b_ip }}"

    - name: Set source and target truenas instance
      set_fact:
        source_truenas_instance: >-
          {% if truenas_master_ip == truenas_a_ip %}
            a
          {% elif truenas_master_ip == truenas_b_ip %}
            b
          {% else %}
            None
          {% endif %}
        target_truenas_instance: >-
          {% if truenas_master_ip == truenas_a_ip %}
            b
          {% elif truenas_master_ip == truenas_b_ip %}
            a
          {% else %}
            None
          {% endif %}

    - name: Set truenas_api_key based on source target instances
      set_fact:
        source_truenas_api_key: "{{ truenas[source_truenas_instance | trim].api_key | default('None') }}"

    - name: Set truenas ssh credentials id and private key id based on source target instances
      set_fact:
        source_truenas_ssh_credentials_id: "{{ truenas_ssh_credentials_id[source_truenas_instance | trim] | int }}"
        source_truenas_ssh_private_key_id: "{{ truenas_ssh_private_key_id[source_truenas_instance | trim] | int }}"

    # - name: Get all existing snapshot tasks on truenas-master
    #   uri:
    #     url: "https://truenas-{{ source_truenas_instance | trim }}.{{ domain }}/api/v2.0/pool/snapshottask"
    #     method: GET
    #     headers:
    #       Authorization: "Bearer {{ source_truenas_api_key | trim }}"
    #       Content-Type: "application/json"
    #     validate_certs: no
    #   register: existing_snapshot_result

    # - name: Start snapshot tasks on truenas-master
    #   uri:
    #     url: "https://truenas-{{ source_truenas_instance | trim }}.{{ domain }}/api/v2.0/pool/snapshottask/id/{{ item }}/run"
    #     method: POST
    #     headers:
    #       Authorization: "Bearer {{ source_truenas_api_key | trim }}"
    #       Content-Type: "application/json"
    #     validate_certs: no
    #   register: snapshot_start_result
    #   loop: "{{ existing_snapshot_result.json | map(attribute='id') | list }}"

    # - name: Get all existing replication tasks on truenas-master
    #   uri:
    #     url: "https://truenas-{{ source_truenas_instance | trim }}.{{ domain }}/api/v2.0/replication"
    #     method: GET
    #     headers:
    #       Authorization: "Bearer {{ source_truenas_api_key | trim }}"
    #       Content-Type: "application/json"
    #     validate_certs: no
    #   register: existing_replication_result

    # - name: Check all replication taks on truenas-master and wait for a running state
    #   uri:
    #     url: "https://truenas-{{ source_truenas_instance | trim }}.{{ domain }}/api/v2.0/replication/id/{{ item }}"
    #     method: GET
    #     headers:
    #       Authorization: "Bearer {{ source_truenas_api_key | trim }}"
    #       Content-Type: "application/json"
    #     validate_certs: no
    #   register: running_replication_result
    #   until: running_replication_result.json.job.state == "RUNNING"
    #   retries: 30
    #   delay: 10
    #   loop: "{{ existing_replication_result.json | map(attribute='id') | list }}"

    # - name: Check all replication taks on truenas-master and wait for a success state
    #   uri:
    #     url: "https://truenas-{{ source_truenas_instance | trim }}.{{ domain }}/api/v2.0/replication/id/{{ item }}"
    #     method: GET
    #     headers:
    #       Authorization: "Bearer {{ source_truenas_api_key | trim }}"
    #       Content-Type: "application/json"
    #     validate_certs: no
    #   register: success_replication_result
    #   until: success_replication_result.json.job.state == "SUCCESS"
    #   retries: 30
    #   delay: 10
    #   loop: "{{ existing_replication_result.json | map(attribute='id') | list }}"

    # - name: Disable existing replication tasks on truenas-master
    #   uri:
    #     url: "https://truenas-{{ source_truenas_instance | trim }}.{{ domain }}/api/v2.0/replication/id/{{ item }}"
    #     method: PUT
    #     headers:
    #       Authorization: "Bearer {{ source_truenas_api_key | trim }}"
    #       Content-Type: "application/json"
    #     validate_certs: no
    #     body_format: json
    #     body:
    #       enabled: false
    #   register: disable_existing_replication_result
    #   loop: "{{ existing_replication_result.json | map(attribute='id') | list }}"

    # - name: Disable existing snapshot tasks on truenas-master
    #   uri:
    #     url: "https://truenas-{{ source_truenas_instance | trim }}.{{ domain }}/api/v2.0/pool/snapshottask/id/{{ item }}"
    #     method: PUT
    #     headers:
    #       Authorization: "Bearer {{ source_truenas_api_key | trim }}"
    #       Content-Type: "application/json"
    #     validate_certs: no
    #     body_format: json
    #     body:
    #       enabled: false
    #   register: disable_existing_snapshot_result
    #   loop: "{{ existing_snapshot_result.json | map(attribute='id') | list }}"

    - name: Get all existing cloud sync tasks on truenas-master
      uri:
        url: "https://truenas-{{ source_truenas_instance | trim }}.{{ domain }}/api/v2.0/cloudsync"
        method: GET
        headers:
          Authorization: "Bearer {{ source_truenas_api_key | trim }}"
          Content-Type: "application/json"
        validate_certs: no
      register: existing_cloudsync_result

    - name: Disable existing cloud sync tasks on truenas-master
      uri:
        url: "https://truenas-{{ source_truenas_instance | trim }}.{{ domain }}/api/v2.0/cloudsync/id/{{ item }}"
        method: PUT
        headers:
          Authorization: "Bearer {{ source_truenas_api_key | trim }}"
          Content-Type: "application/json"
        validate_certs: no
        body_format: json
        body:
          enabled: false
      register: disable_existing_cloudsync_result
      loop: "{{ existing_cloudsync_result.json | map(attribute='id') | list }}"

    - name: Debug
      debug:
        msg: "{{ existing_cloudsync_result }}"


# () Flush local DNS
# () Move VM's to the target Proxmox node
# () Delete containers that uses truenas storage
# (done) Create snapshot task on current master
# (done) Run replication from master to target 
# (done) Disable replication task on current master
# () Disable Cloud Sync on current master
# () Set target as the new master via pfSense API
# ()
# () Flush local DNS on k3s nodes
# () Apply manifests that uses truenas storage
# () Enable replication task on target
