---
- name: "Play to check for firmware updates and apply them when available"
  hosts: localhost
  connection: local
  gather_facts: true

  pre_tasks:
    - name: Include shelly group vars
      ansible.builtin.include_vars: "{{ playbook_dir }}/group_vars/shelly/vars.yaml"

  roles:
    - shelly
