---
- name: K3s master system maintenance
  hosts: k3s_master
  become: true
  serial: 1
  any_errors_fatal: true
  tasks:
    - name: Start rolling-update
      ansible.builtin.include_role:
        name: k3s
        tasks_from: rolling-update

- name: K3s worker system maintenance
  hosts: k3s_worker
  gather_facts: true
  become: true
  become_user: root
  tasks:
    - name: Start system-updates
      ansible.builtin.include_role:
        name: common
        tasks_from: system-updates
