---
- name: Create user
  ansible.builtin.user:
    name: "{{ user_name }}"
    groups: "{{ user_name }}"
    state: present

- name: Add sudo privileges
  ansible.builtin.copy:
    dest: "/etc/sudoers.d/{{ user_name }}"
    content: |
      {{ user_name }} ALL=(ALL) NOPASSWD: ALL
    mode: "0440"
  when: ansible_os_family != "Windows"

- name: Set authorized key taken from file
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', '/home/coen/.ssh/ansible.pub') }}"
    state: present