---
- name: Ensure group exists
  ansible.builtin.group:
    name: "{{ user_name }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    state: present

- name: Allow sudo access for user
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ user_name }}"
    create: true
    mode: "0440"
    line: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
    state: present
  when: user_sudo | default(false)

- name: Add public ssh key to authorized_keys file
  ansible.posix.authorized_key:
    user: "{{ user_name }}"
    key: "{{ lookup('file', ssh.authorized_keys.public_key.control_node_location) }}"
    state: present
  when: user_name == "ansible"
