---
- name: Ensure group exists
  ansible.builtin.group:
    name: "{{ user_name }}"
    state: present

- name: Create user
  ansible.builtin.user:
    name: "{{ user_name }}"
    group: "{{ user_name }}"
    state: present

- name: Allow sudo access for user
  ansible.builtin.lineinfile:
    path: "/etc/sudoers.d/{{ user_name }}"
    create: true
    mode: "0440"
    line: "{{ user_name }} ALL=(ALL) NOPASSWD: ALL"
    validate: "visudo -cf %s"
  when: user_sudo | default(false)
