---
- name: Update apt repo and cache on
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist

- name: Install apt packages
  ansible.builtin.apt:
    pkg:
      - python3-pip
      - git
      - adb
      - curl
      - open-iscsi
    autoclean: true
    autoremove: true
