---
- name: Install python packages
  ansible.builtin.pip:
    name:
      - passlib
      - netaddr

- name: Install python packages with pipx
  community.general.pipx:
    name:
      - ansible-lint
