---
- ansible.builtin.include_tasks: "api-facts.yaml"

- ansible.builtin.include_tasks: "get-all-snapshot-tasks.yaml"

- name: Start snapshot tasks on truenas-master
  uri:
    url: "{{ truenas_api_baseurl }}/pool/snapshottask/id/{{ item }}/run"
    method: POST
    headers:
      Authorization: "Bearer {{ truenas_api_key }}"
      Content-Type: "application/json"
    validate_certs: no
  register: snapshot_start_result
  loop: "{{ existing_snapshot_result.json | map(attribute='id') | list }}"
