metadata:
  annotations:
    node.longhorn.io/default-disks-config: |
      - name: fast-ssd-disk
        path: "/mnt/ssd/data"
        allowScheduling: true
        storageReserved: 0
        tags:
          - ssd
          - fast
      - name: slow-hdd-disk
        path: "/mnt/hdd/data"
        allowScheduling: true
        storageReserved: 0
        tags:
          - hdd
          - slow