---
- name: Read bitnami-sealed-secret-customkeys template file and apply to the k3s cluster
  kubernetes.core.k8s:
    state: present
    template: "bitnami-sealed-secret-customkeys-2.yaml.j2"
  run_once: true

- name: Download bitnami-sealed-secret from github to the first master node
  ansible.builtin.get_url:
    url: "{{ github_infra_manifests }}/{{ item }}.yaml"
    dest: ~/{{ item }}.yaml
    mode: "0664"
  with_items:
    - bitnami-sealed-secrets-manifest
  when: ansible_hostname == hostvars[groups['k3s_master'][0]]['ansible_hostname']

- name: Apply bitnami-sealed-secret to the k3s cluster
  kubernetes.core.k8s:
    apply: true
    state: present
    src: ~/{{ item }}.yaml
  with_items:
    - bitnami-sealed-secrets-manifest
  when: ansible_hostname == hostvars[groups['k3s_master'][0]]['ansible_hostname']

- name: Validate if the bitnami-sealed-secret-controller deployment is available
  kubernetes.core.k8s:
    kind: Deployment
    name: sealed-secrets-controller
    namespace: kube-system
    wait: true
    wait_condition:
      type: Available
      status: "True"
  run_once: true

- name: Validate if bitnami-sealed-secret-controller pod is ready
  kubernetes.core.k8s:
    kind: Pod
    namespace: kube-system
    label_selectors:
      - "name = sealed-secrets-controller"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
  run_once: true
