---
- name: Read bitnami-sealed-secret-customkeys template file and apply to the k3s cluster
  kubernetes.core.k8s:
    state: present
    template: "bitnami-sealed-secret-customkeys-2.yaml.j2"
  run_once: true

- name: Download bitnami-sealed-secret from github to the first master node
  ansible.builtin.get_url:
    url: "{{ github_infra_manifests }}/{{ item }}.yaml"
    dest: ~/{{ item }}.yaml
    mode: "0664"
  with_items:
    - bitnami-sealed-secrets-manifest
  when: ansible_hostname == hostvars[groups['k3s_master'][0]]['ansible_hostname']

- name: Apply bitnami-sealed-secret to the k3s cluster
  kubernetes.core.k8s:
    state: present
    src: ~/{{ item }}.yaml
  with_items:
    - bitnami-sealed-secrets-manifest
  when: ansible_hostname == hostvars[groups['k3s_master'][0]]['ansible_hostname']

- name: Wait until all bitnami-sealed-secret pods are running
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: kube-system
    label_selectors:
      - "name = sealed-secrets-controller"
  register: pod_list
  until: pod_list | json_query('resources[*].status.phase') | unique == ["Running"]
  retries: 15
  delay: 3
  run_once: true