---
- name: Update apt package list
  ansible.builtin.apt:
    update_cache: true

- name: Install dependencies
  ansible.builtin.apt:
    name:
      - apt-transport-https
      - curl
    state: present

- name: Download Microsoft's GPG key
  ansible.builtin.get_url:
    url: https://packages.microsoft.com/keys/microsoft.asc
    dest: /tmp/microsoft.asc
    mode: "0644"

- name: Convert Microsoft's GPG key to a keyring
  ansible.builtin.command:
    cmd:
      gpg --dearmor --output
      /usr/share/keyrings/microsoft-archive-keyring.gpg /tmp/microsoft.asc
    creates: /usr/share/keyrings/microsoft-archive-keyring.gpg

- name: Add the VS Code repository
  ansible.builtin.copy:
    dest: /etc/apt/sources.list.d/vscode.list
    mode: "0644"
    content: |
      deb [arch=amd64 signed-by=/usr/share/keyrings/microsoft-archive-keyring.gpg] https://packages.microsoft.com/repos/vscode stable main

- name: Update apt package list again
  ansible.builtin.apt:
    update_cache: true

- name: Install Visual Studio Code
  ansible.builtin.apt:
    name: code
    state: present
