---
- name: Include var files
  ansible.builtin.include_vars:
    dir: vars

- name: Install avahi-daemon
  apt:
    pkg:
    - avahi-daemon

- name: Enable and start service avahi-daemon, if not started
  service:
    name: avahi-daemon
    state: started
    enabled: yes

- name: Enable avahi reflector
  ansible.builtin.lineinfile:
    path: /etc/avahi/avahi-daemon.conf
    regexp: "^#enable-reflector=no"
    line: "enable-reflector=yes"

- name: Common tasks
  ansible.builtin.include_role:
    name: common

- name: Update system
  ansible.builtin.include_role:
    name: common
    tasks_from: system-updates

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  notify: Reboot
  changed_when: reboot_required_file.stat.exists

- name: Install corosync
  ansible.builtin.include_tasks: install-corosync.yaml

- name: Install Docker
  ansible.builtin.include_tasks: install-docker.yaml

- name: Deploy ser2net
  ansible.builtin.include_tasks: deploy-ser2net.yaml

- name: Deploy cups
  ansible.builtin.include_tasks: deploy-cups.yaml