---
- name: Install corosync
  ansible.builtin.include_tasks: install-corosync.yaml

- name: Find USB devices in /dev/serial/by-id/
  command: find /dev/serial/by-id/ -type l
  register: usb_device_output
  ignore_errors: true

- name: Print USB devices
  debug:
    var: usb_device_output.stdout_lines
  ignore_errors: true

- name: Deploy ser2net
  ansible.builtin.include_tasks: deploy-ser2net.yaml
  when: "'/dev/serial/by-id/usb-0658_0200-if00' in usb_device_output.stdout_lines"

- name: Deploy cups
  ansible.builtin.include_tasks: deploy-cups.yaml
  vars:
    nfs_share_name: cups-config

- name: Cleanup packages
  ansible.builtin.include_role:
    name: common
    tasks_from: system-cleanup
