---
- name: Update system
  ansible.builtin.include_role:
    name: common
    tasks_from: system-updates

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  changed_when: reboot_required_file.stat.exists

- name: Start migration tasks
  when: reboot_required_file.stat.exists
  block:
    - name: Migrate virtual machines
      ansible.builtin.include_tasks: vm-migration.yaml

    - name: Reboot
      ansible.builtin.reboot:
