---
- name: Update system
  ansible.builtin.include_role:
    name: common
    tasks_from: system-updates

- name: Check if reboot required
  ansible.builtin.stat:
    path: /var/run/reboot-required
  register: reboot_required_file
  changed_when: reboot_required_file.stat.exists

- name: Run checkrestart command
  ansible.builtin.command: checkrestart
  register: needs_restart
  changed_when: needs_restart.rc != 0

- name: Print needs restart result
  ansible.builtin.debug:
    var: needs_restart

- name: Start migration tasks
  when: reboot_required_file.stat.exists or 'Found 0 processes using old versions of upgraded files' not in needs_restart.stdout_lines[0]
  block:
    - name: Migrate virtual machines
      ansible.builtin.include_tasks: vm-migration.yaml

    - name: Shutdown TrueNAS VM's
      ansible.builtin.include_tasks: shutdown-truenas-vm.yaml

    - name: Reboot
      ansible.builtin.reboot:
