---
- block:
    - name: Get VM ID by Name
      shell: |
        VM_NAME="truenas-*"
        VM_ID=$(qm list | grep "${VM_NAME}" | awk '{print $1}')
        echo "${VM_ID}"
      register: vm_id_output

    - name: Check VM status
      ansible.builtin.command: "qm status {{ vm_id_output.stdout }}"
      register: vm_status

    - name: Shutdown VM {{ vm_id_output.stdout }} if it's not stopped
      ansible.builtin.command: "qm shutdown {{ vm_id_output.stdout }}"
      when: "'stopped' not in vm_status.stdout"
      register: vm_shutdown

    - name: Print shutdown status
      debug:
        msg: "shutdown status: {{ vm_shutdown }}"
