---
- name: Set timezone
  community.general.timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined) and (system_timezone != "Your/Timezone")

- name: Update apt repo and cache on
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist

- name: Install the latest version of some packages
  ansible.builtin.apt:
    name:
      - nano
      - qemu-guest-agent
      - apparmor
      - open-iscsi
      - avahi-daemon
      - jq
      - lsscsi
      - sg3-utils
      - multipath-tools
      - scsitools
      - parted
    state: latest

- name: Enable IPv4 forwarding
  ansible.posix.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Enable IPv6 forwarding
  ansible.posix.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  when: ansible_all_ipv6_addresses

- name: Enable qemu-guest-agent
  ansible.builtin.systemd:
    name: qemu-guest-agent.service
    state: started
    enabled: true

- name: Creating a multipath.conf file
  ansible.builtin.copy:
    mode: 0644
    dest: "/etc/multipath.conf"
    content: |
      blacklist {
          devnode "sda"
      }
      defaults {
          user_friendly_names yes
          find_multipaths yes
      }

- name: Enable iscsid
  ansible.builtin.systemd:
    name: iscsid.service
    state: started
    enabled: true

- name: Enable multipathd
  ansible.builtin.systemd:
    name: multipathd.service
    state: started
    enabled: true

- name: Extend the logical volume to consume all remaining space in the volume group
  community.general.lvol:
    vg: ubuntu-vg
    lv: ubuntu-lv
    size: +100%FREE

- name: Resize ubuntu-lv filesystem
  ansible.builtin.command: resize2fs /dev/mapper/ubuntu--vg-ubuntu--lv
  register: resize_output
  changed_when: resize_output.rc != 0
