---
- name: Set timezone
  community.general.timezone:
    name: "{{ system_timezone }}"
  when: (system_timezone is defined) and (system_timezone != "Your/Timezone")

- name: Update apt repo and cache on
  ansible.builtin.apt:
    update_cache: true
    cache_valid_time: 3600
    upgrade: dist

- name: Install the latest version packages
  ansible.builtin.apt:
    name:
      - nano
      - qemu-guest-agent
      - apparmor
      - open-iscsi
      - avahi-daemon
      - jq
      - lsscsi
      - sg3-utils
      - multipath-tools
      - scsitools
    state: latest

- name: Enable IPv4 forwarding
  ansible.builtin.sysctl:
    name: net.ipv4.ip_forward
    value: "1"
    state: present
    reload: true

- name: Enable IPv6 forwarding
  ansible.builtin.sysctl:
    name: net.ipv6.conf.all.forwarding
    value: "1"
    state: present
    reload: true
  when: ansible_all_ipv6_addresses

# - name: Enable qemu-guest-agent
#   ansible.builtin.systemd:
#     name: qemu-guest-agent.service
#     state: started
#     enabled: true

- name: Creating a multipath.conf file
  ansible.builtin.copy:
    mode: 0644
    dest: "/etc/multipath.conf"
    content: |
      blacklist {
          devnode "sda"
      }
      defaults {
          user_friendly_names yes
          find_multipaths yes
      }

- name: Enable iscsid
  ansible.builtin.systemd:
    name: iscsid.service
    state: started
    enabled: true

- name: Enable multipathd
  ansible.builtin.systemd:
    name: multipathd.service
    state: started
    enabled: true

# - name: Creating a avahi-daemon.conf file
#   ansible.builtin.copy:
#     dest: "/etc/avahi/avahi-daemon.conf"
#     content: |
#       [server]
#       use-ipv4=yes
#       use-ipv6=no
#       ratelimit-interval-usec=1000000
#       ratelimit-burst=1000
#       [wide-area]
#       enable-wide-area=yes
#       [publish]
#       publish-hinfo=no
#       publish-workstation=no
#       [reflector]
#       enable-reflector=yes
#       reflect-ipv=no
#       [rlimits]
#       #
