---
system_timezone: "Europe/Amsterdam"
localdomain: "lan.stamx.nl"

nfs:
  server: "truenas-master.{{ localdomain }}"

ssh:
  authorized_keys:
    public_key:
      control_node_location: "/home/coen/.ssh/ansible.pub"

test: "/home/coen/.ssh/ansible.pub"