---
- name: Read bitnami-sealed-secret-customkeys template file and apply to the k3s cluster
  kubernetes.core.k8s:
    state: present
    template: "bitnami-sealed-secret-customkeys-2.yaml.j2"
  run_once: true

- name: Download manifest from github and apply to the k3s cluster
  ansible.builtin.include_tasks: deploy.yaml
  run_once: true
  when: '"github" in manifest.source'

- name: Validate if pod is ready
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: kube-system
    label_selectors:
      - "name = sealed-secrets-controller"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
  run_once: true
