---
- name: Get latest stable kubectl version if 'stable' is specified
  ansible.builtin.uri:
    url: https://dl.k8s.io/release/stable.txt
    return_content: true
  register: stable_version
  when: kubectl.version == 'stable'

- name: Set resolved kubectl version
  ansible.builtin.set_fact:
    resolved_kubectl_version: "{{ stable_version.content | trim }}"
  when: kubectl.version == 'stable'

- name: Use provided kubectl version if not 'stable'
  ansible.builtin.set_fact:
    resolved_kubectl_version: "{{ kubectl.version }}"
  when: kubectl.version != 'stable'

- name: Check if kubectl is installed
  ansible.builtin.command:
    cmd: which kubectl
  register: kubectl_installed
  ignore_errors: true
  changed_when: false

- name: Get the current kubectl version
  ansible.builtin.command:
    cmd: kubectl version --client=true --output="json"
  register: kubectl_version
  ignore_errors: true
  changed_when: false
  when: kubectl_installed.rc == 0

- name: Set current kubectl version
  ansible.builtin.set_fact:
    current_kubectl_version: "{{ kubectl_version.stdout | from_json | json_query('clientVersion.gitVersion') }}"
  when: kubectl_installed.rc == 0

- name: Remove existing kubectl version directory if it differs
  ansible.builtin.file:
    path: "/opt/kubectl-{{ current_kubectl_version }}"
    state: absent
  when: kubectl_installed.rc == 0 and current_kubectl_version != resolved_kubectl_version
  become: true

- name: Create kubectl versioned directory
  ansible.builtin.file:
    path: "/opt/kubectl-{{ resolved_kubectl_version }}"
    state: directory
    mode: "0755"
  become: true

- name: Download the kubectl binary if not already present
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ resolved_kubectl_version }}/bin/linux/amd64/kubectl"
    dest: "/opt/kubectl-{{ resolved_kubectl_version }}/kubectl"
    mode: "0755"
    force: false
  become: true

- name: Get kubectl binary sha256sum
  ansible.builtin.stat:
    path: "/opt/kubectl-{{ resolved_kubectl_version }}/kubectl"
    checksum_algorithm: sha256
  register: kubectl_stat

- name: Set sha256sum of kubectl binary
  ansible.builtin.set_fact:
    kubectl_binary_sha256: "{{ kubectl_stat.stat.checksum | default('') }}"
  when: kubectl_stat.stat.exists

- name: Download the kubectl binary checksum
  ansible.builtin.get_url:
    url: "https://dl.k8s.io/release/{{ resolved_kubectl_version }}/bin/linux/amd64/kubectl.sha256"
    dest: "/opt/kubectl-{{ resolved_kubectl_version }}/kubectl.sha256"
    mode: "0644"
  become: true

- name: Read the downloaded kubectl checksum
  ansible.builtin.slurp:
    src: "/opt/kubectl-{{ resolved_kubectl_version }}/kubectl.sha256"
  register: kubectl_checksum_file
  become: true

- name: Set kubectl checksum fact
  ansible.builtin.set_fact:
    kubectl_checksum_sha256: "{{ kubectl_checksum_file['content'] | b64decode | trim }}"

- name: Assert that the kubectl binary is OK
  ansible.builtin.assert:
    that:
      - kubectl_binary_sha256 | trim == kubectl_checksum_sha256 | trim
    fail_msg: "The sha256sum of the kubectl binary does not match the expected checksum."
    success_msg: "kubectl sha256 checksum verified successfully."

- name: Create a symlink to kubectl
  ansible.builtin.file:
    src: "/opt/kubectl-{{ resolved_kubectl_version }}/kubectl"
    dest: "/usr/bin/kubectl"
    state: link
  become: true

- name: Remove kubectl directory if checksum is invalid
  ansible.builtin.file:
    path: "/opt/kubectl-{{ resolved_kubectl_version }}"
    state: absent
  when: kubectl_binary_sha256 | trim != kubectl_checksum_sha256 | trim
  become: true
