---
- name: Read metallb template file and apply to the k3s cluster
  kubernetes.core.k8s:
    state: present
    template: "app-metallb.yaml.j2"
  run_once: true

- name: Validate if pod is ready | metallb
  kubernetes.core.k8s_info:
    kind: Pod
    name: metallb-controller
    namespace: metallb-system
    label_selectors:
      - "app.kubernetes.io/name=metallb"
      - "app.kubernetes.io/component=controller"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
  run_once: true

- name: Read metallb-addresspool template file and apply to the k3s cluster
  kubernetes.core.k8s:
    state: present
    template: "app-metallb-addresspool.yaml.j2"
  run_once: true
