---
- name: Test namespace {{ item.namespace }}
  ansible.builtin.include_tasks: namespace.yaml
  when: item.namespace is defined

- name: Download manifest from github and apply to the k3s cluster for {{ item.name }}
  ansible.builtin.include_tasks: deploy.yaml
  when: '"github" in item.source'

- name: Validate if pods are ready for {{ item.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "devops"
    label_selectors:
      - "{{ labels }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
    wait_sleep: 10
    wait_timeout: 360
  with_items:
    - "app=drone-server"
    - "app=drone-runner-docker"
    - "app=drone-secrets"
  loop_control:
    loop_var: labels
