---
- name: Download manifest from github and apply to the k3s cluster
  block:
    - name: Create manifests directory on first master
      file:
        path: ~/temp
        state: directory
        owner: root
        group: root
        mode: 0644
      register: temp_dir

    - name: Download {{ item.name }}
      ansible.builtin.get_url:
        url: "{{ github_infra_manifests_url }}/{{ item.name }}.yaml"
        dest: "{{ temp_dir.path }}/{{ item.name }}.yaml"
        mode: "0664"

    - name: Apply {{ item.name }}
      kubernetes.core.k8s:
        apply: true
        state: present
        src: "{{ temp_dir.path }}/{{ item.name }}.yaml"
        validate:
          fail_on_error: true
  when: ansible_hostname == hostvars[groups["k3s_master"][0]]["ansible_hostname"]

- name: Download manifest from github and apply to the k3s cluster
  ansible.builtin.include_tasks: deploy.yaml
