---
- name: Get list of ArgoCD applications with label storage=truenas
  shell: |
    kubectl get applications -l storage=truenas -o jsonpath='{.items[*].metadata.name}' -n argocd
  register: app_list
  changed_when: false
  run_once: true

- name: Patch each ArgoCD application
  shell: |
    kubectl patch app {{ item }} -n argocd --type=merge -p '{"metadata": {"finalizers": ["resources-finalizer.argocd.argoproj.io"]}}'
  loop: "{{ app_list.stdout.split() }}"
  when: app_list.stdout != ""
  run_once: true

- name: Delete ArgoCD application
  shell: |
    kubectl delete app {{ item }} -n argocd
  loop: "{{ app_list.stdout.split() }}"
  when: app_list.stdout != ""
  run_once: true
