---
- name: Create namespace | {{ argocd.name }}
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ argocd.namespace }}"
    state: present
  run_once: true

- name: Download public manifest | {{ argocd.name }}
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/argoproj/argo-cd/{{ argocd.version }}/manifests/core-install.yaml
    dest: ~/argocd-core.yaml
    mode: "0664"
  run_once: true

- name: Apply manifest to the cluster | {{ argocd.name }}
  kubernetes.core.k8s:
    namespace: "{{ argocd.namespace }}"
    state: present
    src: ~/argocd-core.yaml
  run_once: true

- name: Download parent-app | {{ argocd.name }}
  ansible.builtin.get_url:
    url: https://raw.githubusercontent.com/theautomation/gitops/main/argocd/parent-app.yaml
    dest: ~/parent-app.yaml
    mode: "0664"
    force: true
  run_once: true

- name: Apply parent-app to the cluster | {{ argocd.name }}
  kubernetes.core.k8s:
    state: present
    src: ~/parent-app.yaml
  run_once: true
