---
- name: Include var files
  ansible.builtin.include_vars:
    dir: vars

- name: Include prerequisites task
  ansible.builtin.include_tasks: "prerequisites.yaml"

- name: Include k3s task
  ansible.builtin.include_tasks: "k3s.yaml"
