---
- name: Create namespace | {{ democratic_csi_manual.name }}
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ democratic_csi_manual.namespace }}"
    state: present
  run_once: true

- name: Read template file and apply to the k3s cluster | {{ democratic_csi_manual.name }}
  kubernetes.core.k8s:
    state: present
    template: "{{ democratic_csi_manual.name }}-manual.yaml.j2"
  run_once: true

- name: Wait until all pods are running | {{ democratic_csi_manual.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ democratic_csi_manual.namespace }}"
    label_selectors:
      - "app.kubernetes.io/name={{ democratic_csi_manual.name }}"
  register: pod_list
  until: pod_list | json_query('resources[*].status.phase') | unique == ["Running"]
  retries: 15
  delay: 3
  run_once: true

- name: Render template to localhost | {{ democratic_csi_manual.name }}
  ansible.builtin.include_tasks: render-template.yaml
  vars:
    template_file: "{{ democratic_csi_manual.name }}-manual.yaml.j2"
