---
- name: Create namespace | {{ drone.name }}
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ drone.namespace }}"
    state: present
  run_once: true

- name: Read template file and apply to the k3s cluster | {{ drone.name }}
  kubernetes.core.k8s:
    state: present
    template: "{{ drone.name }}.yaml.j2"
  run_once: true

- name: Validate if pods is ready | {{ label }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ drone.namespace }}"
    label_selectors:
      - "app={{ label }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
  loop_control:
    loop_var: label
  vars:
    label:
      - "{{ drone.name }}-server"
      - "{{ drone.name }}-runner-docker"
      - "{{ drone.name }}-secrets"
  run_once: true

- name: Render template to localhost | {{ drone.name }}
  ansible.builtin.include_tasks: render-template.yaml
  vars:
    template_file: "{{ drone.name }}.yaml.j2"
