---
- name: Create namespaces
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ item }}"
    state: present
  loop: "{{ github_registry.credentials.namespaces }}"
  run_once: true
  when: github_registry.credentials.deploy

- name: Apply github registry credentials in the defined namespace list
  kubernetes.core.k8s:
    state: present
    template: github-registry-credentials.yaml.j2
  loop: "{{ github_registry.credentials.namespaces }}"
  loop_control:
    loop_var: github_registry_credentials_namespace
  run_once: true
  when: github_registry.credentials.deploy

- name: Output template file to localhost
  ansible.builtin.template:
    src: github-registry-credentials.yaml.j2
    dest: "{{ output_file_location }}{{ github_registry.credentials.name }}-{{ github_registry_credentials_namespace }}.yaml"
    mode: '0644'
  loop: "{{ github_registry.credentials.namespaces }}"
  loop_control:
    loop_var: github_registry_credentials_namespace
  delegate_to: localhost
  run_once: true
