---
- name: Create namespace | {{ harbor.namespace }}
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ harbor.namespace }}"
    state: present
  run_once: true

- name: Read template file and apply to the k3s cluster | {{ harbor.name }}
  kubernetes.core.k8s:
    state: present
    template: "{{ harbor.name }}.yaml.j2"
  run_once: true

- name: Wait until all pods are running | {{ harbor.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ harbor.namespace }}"
    label_selectors:
      - "app={{ harbor.name }}"
  register: pod_list
  until: pod_list | json_query('resources[*].status.phase') | unique == ["Running"]
  retries: 15
  delay: 10
  run_once: true

- name: Render template to localhost | {{ harbor.name }}
  ansible.builtin.include_tasks: render-template.yaml
  vars:
    template_file: "{{ harbor.name }}.yaml.j2"
