---
- name: Create namespace | {{ ingress_nginx.name }}-{{ ingress_nginx.namespaces }}
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ ingress_nginx_namespace }}"
    state: present
  run_once: true
  loop: "{{ ingress_nginx.namespaces }}"
  loop_control:
    loop_var: ingress_nginx_namespace

- name: Read template file and apply to the k3s cluster | {{ ingress_nginx.name }}-{{ ingress_nginx.namespaces }}
  kubernetes.core.k8s:
    state: present
    template: "{{ ingress_nginx.name }}.yaml.j2"
  run_once: true
  loop: "{{ ingress_nginx.namespaces }}"
  loop_control:
    loop_var: ingress_nginx_namespace

- name: Validate if pod is ready | {{ ingress_nginx.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ ingress_nginx_namespace }}"
    label_selectors:
      - "app.kubernetes.io/component=controller"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
  run_once: true
  loop: "{{ ingress_nginx.namespaces }}"
  loop_control:
    loop_var: ingress_nginx_namespace

- name: Output template file to localhost
  ansible.builtin.template:
    src: "{{ ingress_nginx.name }}.yaml.j2"
    dest: "{{ output_file_location }}{{ ingress_nginx.name }}-{{ ingress_nginx_namespace }}.yaml"
    mode: '0644'
  loop: "{{ ingress_nginx.namespaces }}"
  loop_control:
    loop_var: ingress_nginx_namespace
  delegate_to: localhost
  run_once: true
