---
- name: Create namespace | {{ node_feature_discovery.name }}
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ node_feature_discovery.namespace }}"
    state: present
  run_once: true

- name: Read template file and apply to the k3s cluster | {{ node_feature_discovery.name }}
  kubernetes.core.k8s:
    state: present
    template: "{{ node_feature_discovery.name }}.yaml.j2"
  run_once: true

- name: Wait until all pods are running | {{ node_feature_discovery.name }}
  kubernetes.core.k8s_info:
    kind: Pod
    namespace: "{{ node_feature_discovery.namespace }}"
    label_selectors:
      - "app.kubernetes.io/name = {{ node_feature_discovery.name }}"
  register: pod_list
  until: pod_list | json_query('resources[*].status.phase') | unique == ["Running"]
  retries: 15
  delay: 3
  run_once: true

- name: Render template to localhost | {{ node_feature_discovery.name }}
  ansible.builtin.include_tasks: render-template.yaml
  vars:
    template_file: "{{ node_feature_discovery.name }}.yaml.j2"
