---
- name: Create namespaces
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ item }}"
    state: present
  loop: "{{ private_registry.credentials.namespaces }}"
  run_once: true
  when: private_registry.credentials.deploy

- name: Apply private registry credentials in the defined namespace list
  kubernetes.core.k8s:
    state: present
    template: private-registry-credentials.yaml.j2
  loop: "{{ private_registry.credentials.namespaces }}"
  loop_control:
    loop_var: private_registry_credentials_namespace
  run_once: true
  when: private_registry.credentials.deploy

- name: Output template file to localhost
  ansible.builtin.template:
    src: private-registry-credentials.yaml.j2
    dest: "{{ output_file_location }}{{ private_registry.credentials.name }}-{{ private_registry_credentials_namespace }}.yaml"
    mode: '0644'
  loop: "{{ private_registry.credentials.namespaces }}"
  loop_control:
    loop_var: private_registry_credentials_namespace
  delegate_to: localhost
  run_once: true
