---
- name: Create namespaces for {{ tls_certificates.wildcard_theautomation_nl.name }}
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ item }}"
    state: present
  loop: "{{ tls_certificates.wildcard_theautomation_nl.namespaces }}"
  run_once: true
  when: tls_certificates.wildcard_theautomation_nl.deploy

- name: Create namespaces for {{ tls_certificates.wildcard_lan_theautomation_nl.name }}
  kubernetes.core.k8s:
    kind: Namespace
    api_version: v1
    name: "{{ item }}"
    state: present
  loop: "{{ tls_certificates.wildcard_lan_theautomation_nl.namespaces }}"
  run_once: true
  when: tls_certificates.wildcard_lan_theautomation_nl.deploy

- name: Apply theautomation.nl wildcard TLS certs in the defined namespace list
  kubernetes.core.k8s:
    state: present
    template: tls-wildcard-theautomation-nl.yaml.j2
  loop: "{{ tls_certificates.wildcard_theautomation_nl.namespaces }}"
  loop_control:
    loop_var: tls_wildcard_theautomation_nl_namespace
  run_once: true
  when: tls_certificates.wildcard_theautomation_nl.deploy

- name: Output template file to localhost
  ansible.builtin.template:
    src: tls-wildcard-theautomation-nl.yaml.j2
    dest: "{{ output_file_location }}{{ tls_certificates.wildcard_theautomation_nl.name }}-{{ tls_wildcard_theautomation_nl_namespace }}.yaml"
    mode: '0644'
  loop: "{{ tls_certificates.wildcard_theautomation_nl.namespaces }}"
  loop_control:
    loop_var: tls_wildcard_theautomation_nl_namespace
  delegate_to: localhost
  run_once: true
  when: tls_certificates.wildcard_theautomation_nl.deploy

- name: Apply lan.theautomation.nl wildcard TLS certs in the defined namespace list
  kubernetes.core.k8s:
    state: present
    template: tls-wildcard-lan-theautomation-nl.yaml.j2
  loop: "{{ tls_certificates.wildcard_lan_theautomation_nl.namespaces }}"
  loop_control:
    loop_var: tls_wildcard_lan_theautomation_nl_namespace
  run_once: true
  when: tls_certificates.wildcard_lan_theautomation_nl.deploy

- name: Output template file to localhost
  ansible.builtin.template:
    src: tls-wildcard-lan-theautomation-nl.yaml.j2
    dest: "{{ output_file_location }}{{ tls_certificates.wildcard_lan_theautomation_nl.name }}-{{ tls_wildcard_lan_theautomation_nl_namespace }}.yaml"
    mode: '0644'
  loop: "{{ tls_certificates.wildcard_lan_theautomation_nl.namespaces }}"
  loop_control:
    loop_var: tls_wildcard_lan_theautomation_nl_namespace
  delegate_to: localhost
  run_once: true
  when: tls_certificates.wildcard_lan_theautomation_nl.deploy