---
- name: Apply k8s.lan wildcard TLS certs in the defined namespace list
  kubernetes.core.k8s:
    state: present
    template: tls-wildcard-k8s-lan.yaml.j2
  loop: "{{ tls_wildcard_k8s_lan_namespaces }}"
  loop_control:
    loop_var: tls_wildcard_k8s_lan_namespace
  run_once: true

- name: Apply theautomation.nl wildcard TLS certs in the defined namespace list
  kubernetes.core.k8s:
    state: present
    template: tls-wildcard-theautomation-nl.yaml.j2
  loop: "{{ tls_wildcard_theautomation_nl_namespaces }}"
  loop_control:
    loop_var: tls_wildcard_theautomation_nl_namespace
  run_once: true
