---
- name: Drain node
  ansible.builtin.include_tasks: "drain.yaml"

- name: Update system
  ansible.builtin.include_role:
    name: common
    tasks_from: system-updates

- name: Reboot the system
  ansible.builtin.reboot:

- name: Wait for the system to come back online
  ansible.builtin.wait_for_connection:

- name: Uncordon nodes
  ansible.builtin.include_tasks: "uncordon.yaml"

- name: Wait for node to become ready
  kubernetes.core.k8s_info:
    kind: node
    label_selectors:
      - "kubernetes.io/hostname = {{ ansible_hostname }}"
    wait: true
    wait_condition:
      type: Ready
      status: "True"
  retries: 3
  delay: 5
