---
- name: Get current settings from device {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings
    body_format: json
    return_content: true
  register: settings_content
  ignore_errors: true

- name: Set device name for lights from inventory var {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings/light/0?name={{ hostvars[item]['device_name'] }}
  changed_when: settings_content.json.lights[0].name != hostvars[item]['device_name']
  when: "'SHDM' in settings_content.json.device.type"
  ignore_errors: true

- name: Set device name for bulps from inventory var {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings?name={{ hostvars[item]['device_name'] }}
  changed_when: settings_content.json.name != hostvars[item]['device_name']
  when: "'SHCB' in settings_content.json.device.type"
  ignore_errors: true

- name: Set device name for relays from inventory var {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings?name={{ hostvars[item]['device_name'] }}
  changed_when: settings_content.json.name != hostvars[item]['device_name']
  when: "'SHPLG' in settings_content.json.device.type or 'SHSW' in settings_content.json.device.type"
  ignore_errors: true

- name: Start name task
  ansible.builtin.include_tasks: name.yaml
  ignore_errors: true

- name: Enable/disable ap roaming for {{ device_name.json.name }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings?ap_roaming_enabled={{ settings.ap_roaming.enable }}
  changed_when: settings_content.json.ap_roaming.enabled != settings.ap_roaming.enable
  ignore_errors: true

- name: Set ap roaming rssi threshold for {{ device_name.json.name }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings?ap_roaming_threshold={{ settings.ap_roaming.rssi_threshold }}
  changed_when: settings_content.json.ap_roaming.threshold != settings.ap_roaming.rssi_threshold
  ignore_errors: true

- name: Enable/disable coiot and set peer for {{ device_name.json.name }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings?coiot_enable={{ settings.coiot.enable }}&coiot_peer={{ settings.coiot.peer }}
  changed_when: settings_content.json.coiot.enabled != settings.coiot.enable or settings_content.json.coiot.peer != settings.coiot.peer
  ignore_errors: true

- name: Enable/disable sntp and set address for {{ device_name.json.name }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings?sntp_enable={{ settings.sntp.enable }}&sntp_server={{ settings.sntp.server }}
  changed_when: settings_content.json.sntp.enabled != settings.sntp.enable or settings_content.json.sntp.server != settings.sntp.server
  ignore_errors: true

- name: Enable/disable eco mode {{ device_name.json.name }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings?eco_mode_enabled={{ settings.eco_mode_enabled }}
  changed_when: settings_content.json.eco_mode_enabled != settings.eco_mode_enabled

- name: Enable/disable relays default state {{ device_name.json.name }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings/relay/0?default_state={{ settings.default_state }}
  changed_when: settings_content.json.relays[0].default_state != settings.default_state
  when: "'SHPLG' in settings_content.json.device.type or 'SHSW' in settings_content.json.device.type"
  ignore_errors: true

- name: Enable/disable lights default state {{ device_name.json.name }}
  ansible.builtin.uri:
    url: http://{{ item }}/settings/light/0?default_state={{ settings.default_state }}
  changed_when: settings_content.json.lights[0].default_state != settings.default_state
  when: "'lights' in settings_content.json"
  ignore_errors: true
