---
- name: Get sys config from {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/rpc/Sys.GetConfig
    body_format: json
    return_content: true
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

- name: Set sys config for {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    body_format: json
    method: POST
    url: http://{{ item }}/rpc
    body: |
      {
        "id": 1,
        "method": "Sys.SetConfig",
        "params": {
          "config": {
            "device": {
              "name": "{{ hostvars[item]['device_name'] }}",
              "eco_mode": {{ settings.eco_mode_enabled }}
            },
            "sntp": {
              "server": "{{ settings.sntp.server }}"
            }
          }
        }
      }
  register: result
  changed_when: result.json.device.name != hostvars[item]['device_name']
  until: result.status == 200
  retries: 10
  delay: 5

- name: Get wifi config from {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/rpc/Wifi.GetConfig
    body_format: json
    return_content: true
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

- name: Set wifi config for {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    body_format: json
    method: POST
    url: http://{{ item }}/rpc
    body: |
      {
        "id": 1,
        "method": "WiFi.SetConfig",
        "params": {
          "config": {
            "ap": {
              "enable": {{ settings.ap.enable }}
            },
            "roam": {
              "rssi_thr": {{ settings.ap_roaming.enable | ternary(settings.ap_roaming.rssi_threshold | int, -80) }}
            }
          }
        }
      }
  register: result
  changed_when: result.json.ap.enable != settings.ap.enable or
    result.json.roam.rssi_thr != settings.ap_roaming.rssi_threshold
  until: result.status == 200
  retries: 10
  delay: 5

- name: Get switch config from {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/rpc/Switch.GetConfig?id=0
    body_format: json
    return_content: true
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

- name: Set switch config for {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    body_format: json
    method: POST
    url: http://{{ item }}/rpc
    body: |
      {
        "id": 0,
        "method": "Switch.SetConfig",
        "params": {
          "config": {
            "voltage_limit": {{ settings.voltage_limit }}
          }
        }
      }
  register: result
  changed_when: result.json.voltage_limit != settings.voltage_limit
  until: result.status == 200
  retries: 10
  delay: 5

- name: Get outbound websocket config from {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/rpc/WS.GetConfig
    body_format: json
    return_content: true
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

- name: Set websocket config for {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    body_format: json
    method: POST
    url: http://{{ item }}/rpc
    body: |
      {
        "id": 1,
        "method": "WS.SetConfig",
        "params": {
          "config": {
            "enable": {{ settings.websocket.enable }},
            "server": "{{ settings.websocket.server }}"
          }
        }
      }
  register: result
  changed_when: result.json.enable != settings.websocket.enable or
    result.json.server != settings.websocket.server
  until: result.status == 200
  retries: 10
  delay: 5

- name: Get BLE config from {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/rpc/BLE.GetConfig
    body_format: json
    return_content: true
  register: result
  until: result.status == 200
  retries: 10
  delay: 5

- name: Set BLE config for {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    body_format: json
    method: POST
    url: http://{{ item }}/rpc
    body: |
      {
        "id": 1,
        "method": "BLE.SetConfig",
        "params": {
          "config": {
            "enable": {{ settings.bluetooth.enable }},
            "rpc": {
              "enable": {{ settings.bluetooth.enable_rpc }}
            },
            "observer": {
              "enable": {{ settings.bluetooth.enable_gateway }}
            }
          }
        }
      }
  register: result
  changed_when: result.json.enable != settings.bluetooth.enable or
    result.json.rpc.enable != settings.bluetooth.enable_rpc or
    result.json.observer.enable != settings.bluetooth.enable_gateway
  until: result.status == 200
  retries: 10
  delay: 5
