---
- name: Get sys config from {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/rpc/Sys.GetConfig
    body_format: json
    return_content: true
  register: sysconfig_content
  ignore_errors: true

- name: Set sys config for {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    body_format: json
    method: POST
    url: http://{{ item }}/rpc
    body: |
      {
        "id": 1,
        "method": "Sys.SetConfig",
        "params": {
          "config": {
            "device": {
              "name": "{{ hostvars[item]['device_name'] }}",
              "eco_mode": {{ settings.eco_mode_enabled }}
            },
            "sntp": {
              "server": "{{ settings.sntp.server }}"
            }
          }
        }
      }
  changed_when: sysconfig_content.json.device.name != hostvars[item]['device_name']
  ignore_errors: true

- name: Get wifi config from {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/rpc/Wifi.GetConfig
    body_format: json
    return_content: true
  register: wificonfig_content
  ignore_errors: true

- name: Set wifi config for {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    body_format: json
    method: POST
    url: http://{{ item }}/rpc
    body: |
      {
        "id": 1,
        "method": "WiFi.SetConfig",
        "params": {
          "config": {
            "ap": {
              "enable": {{ settings.ap.enable }}
            },
            "roam": {
              "rssi_thr": {{ settings.ap_roaming.enable | ternary(settings.ap_roaming.rssi_threshold | int, -80) }}
            }
          }
        }
      }
  changed_when: wificonfig_content.json.ap.enable != settings.ap.enable or
    wificonfig_content.json.roam.rssi_thr != settings.ap_roaming.rssi_threshold
  ignore_errors: true

- name: Get switch config from {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/rpc/Switch.GetConfig?id=0
    body_format: json
    return_content: true
  register: switchconfig_content
  ignore_errors: true

- name: Set switch config for {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    body_format: json
    method: POST
    url: http://{{ item }}/rpc
    body: |
      {
        "id": 0,
        "method": "Switch.SetConfig",
        "params": {
          "config": {
            "voltage_limit": {{ settings.voltage_limit }}
          }
        }
      }
  changed_when: switchconfig_content.json.voltage_limit != settings.voltage_limit
  ignore_errors: true

- name: Get outbound websocket config from {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    url: http://{{ item }}/rpc/WS.GetConfig
    body_format: json
    return_content: true
  register: wsconfig_content
  ignore_errors: true

- name: Set websocket config for {{ hostvars[item]['device_name'] }}
  ansible.builtin.uri:
    body_format: json
    method: POST
    url: http://{{ item }}/rpc
    body: |
      {
        "id": 1,
        "method": "WS.SetConfig",
        "params": {
          "config": {
            "enable": {{ settings.websocket.enable }},
            "server": "{{ settings.websocket.server }}"
          }
        }
      }
  changed_when: wsconfig_content.json.enable != settings.websocket.enable or
    wsconfig_content.json.server != settings.websocket.server
  ignore_errors: true
