---
- name: Update packaged cache
  ansible.builtin.import_role:
    name: system-update-package-cache

- name: Ensure nfs-common is installed
  ansible.builtin.package:
    name: nfs-common
    state: present
