---
# IP-address of first master node
server_ip: "{{ hostvars[groups['k3s_master'][0]]['ansible_default_ipv4']['address'] }}"

# The location to store rendered jinja2 templates like deployments .yaml files
output_file_location: "/home/coen/Downloads/"

argocd:
  deploy: true
  name: argocd-core
  namespace: argocd
  version: "stable"

democratic_csi_manual:
  deploy: true
  name: democratic-csi
  namespace: democratic-csi
  image_tag:
    cleanup: "1.32.0"
    csi_proxy: latest
    democratic_csi: latest
    driver_registrar: v2.5.0

kube_vip:
  deploy: true
  name: "kube-vip"
  namespace: "kube-system"
  image_tag: "v0.7.2"
  apiserver_endpoint: "10.0.100.100"
  flannel_iface: "ens18"

sealed_secrets:
  deploy: true
  name: "sealed-secrets"
  namespace: "kube-system"
  image_tag: "v0.26.2"

node_feature_discovery:
  deploy: false
  name: node-feature-discovery
  namespace: devops
  image_tag:
    node_feature_discovery: "v0.12.1"

tls_certificates:
  wildcard_theautomation_nl:
    deploy: true
    name: "wildcard-theautomation-nl"
    namespaces:
      - devops
      - media
      - home-automation
      - tools
  wildcard_lan_theautomation_nl:
    deploy: true
    name: "wildcard-lan-theautomation-nl"
    namespaces:
      - devops
      - media
      - home-automation
      - tools

github_registry:
  credentials:
    deploy: true
    name: github-registry-creds
    namespaces:
      - devops
      - home-automation
      - tools
