---
- name: Set timezone
  community.general.timezone:
    name: "{{ system_timezone }}"
  when: system_timezone is defined

- name: Set authorized key taken from file
  authorized_key:
    user: root
    state: present
    key: "{{ lookup('file', '/home/coen/.ssh/ansible.pub') }}"

- name: Set the hostname using hostnamectl
  command: hostnamectl set-hostname "{{ inventory_hostname }}"