---
- name: Set timezone
  community.general.timezone:
    name: "{{ system_timezone }}"
  when: system_timezone is defined

- name: Include hostname task
  ansible.builtin.include_tasks: hostname.yaml
