---
git:
  user:
    name: "x-real-ip"
    email: "c.github@stamx.nl"
  token: "{{ vault_git_token }}"
  clone_user_repos: true
  excluded_repos:
    - "backup-to-cloud"
    - "rsync-container"
    - "workorder"
    - "grafana"
    - "reverse-proxy"

# List of mountpoints to create
# The mountpoints will be created in /mnt
mount:
  directory: "/mnt"
  points:
    - folder: "shared"
      nfs_path: "/mnt/ssd/webdav"
    - folder: "backups"
      nfs_path: "/mnt/ssd/backups"
    - folder: "coen"
      nfs_path: "/mnt/hdd/coen"
    - folder: "anne"
      nfs_path: "/mnt/hdd/anne"
    - folder: "plex-media"
      nfs_path: "/mnt/hdd/containers/k8s/plex-media"
    - folder: "proxmmox-backups"
      nfs_path: "/mnt/hdd/backups/proxmox"
