---
- name: "Play for desktops"
  hosts: localhost
  connection: local
  become: true
  roles:
    - "../roles/common/basic"
    - "../roles/desktop"
  vars:
    username: anne
    password: welkom01
  tasks:

    - name: Create new user
      user:
        name: "{{ username }}"
        password: "{{ password | password_hash('sha512') }}"
        createhome: true
        shell: /bin/bash
        state: present

    - name: Add user to sudo group
      user:
        name: "{{ username }}"
        groups: sudo
        append: true
