---
- name: Cordon all k3s nodes
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Cordon nodes
      ansible.builtin.include_role:
        name: k3s
        tasks_from: cordon

- name: Drain all k3s nodes
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Drain nodes
      ansible.builtin.include_role:
        name: k3s
        tasks_from: drain
