# - name: Play for k3s cluster (masters and workers)
#   hosts: k3s_cluster
#   gather_facts: true
#   become: true
#   roles:
#     - "../roles/common/basic"
#     - "../roles/kubernetes/os"
#     - "../roles/kubernetes/k3s"

- name: Play to add settings for the k3s masters
  hosts: k3s_master
  gather_facts: true
  become: true
  roles:
    - "../roles/kubernetes/resources"
