- name: Play to start apply all ArgoCD applications
  hosts: k3s_master
  become: true
  tasks:
    - name: Apply ArgoCD and app-of-apps
      ansible.builtin.include_role:
        name: kubernetes
        tasks_from: argocd-app-of-apps
