---
- name: Cordon all k3s nodes
  hosts: k3s_cluster
  become: true
  roles:
    - "../roles/kubernetes/cordon_nodes"

- name: Drain all k3s nodes
  hosts: k3s_cluster
  become: true
  roles:
    - "../roles/kubernetes/maintenance/tasks/drain_nodes.yaml"
