---
- name: Add host key to local known_hosts
  hosts: localhost
  gather_facts: false
  vars:
    host_groups:
      - proxmox
      - k3s_cluster

  tasks:
    - name: Collect all hosts from selected groups
      set_fact:
        host_groups: "{{ host_groups | map('extract', groups) | list | flatten | unique }}"

    - name: Add hosts to known_hosts
      ansible.builtin.known_hosts:
        path: "{{ lookup('env','HOME') }}/.ssh/known_hosts"
        name: "{{ item }}"
        key: "{{ lookup('pipe', 'ssh-keyscan -T 5 ' + item) }}"
      loop: "{{ host_groups }}"
