---
- name: "Play to setup snapshots tasks in TrueNAS"
  hosts: truenas
  become: false
  remote_user: admin
  gather_facts: false
  tasks:
    - name: Delete all snapshot tasks
      ansible.builtin.include_role:
        name: truenas
        tasks_from: delete-pool-snapshot-tasks.yaml

    - name: Create desired snapshots on TrueNAS
      ansible.builtin.include_role:
        name: truenas
        tasks_from: create-pool-snapshot-tasks.yaml
