---
- name: Wait for {{ item }} to become up
  ansible.builtin.uri:
    url: http://{{ item }}/status
    body_format: json
    method: POST
    return_content: true
  register: status_content
  until: status_content.json.uptime | int >= 10

- name: Check for available updates on device {{ item }}
  ansible.builtin.uri:
    url: http://{{ item }}/ota/check
    body_format: json
    method: POST
    return_content: true
  register: ota_check_content
  until: ota_check_content.json.status == "ok"

- name: Register OTA content from device {{ item }}
  ansible.builtin.uri:
    url: http://{{ item }}/ota
    body_format: json
    method: POST
    return_content: true
  register: ota_content
  until: ota_content.json.status != "unknown"

- name: Update firmware if update is available
  block:
    - name: Show firmware versions for device {{ item }}
      ansible.builtin.debug:
        msg:
          - Old firmware version is {{ ota_content.json.old_version }}
          - New firmware version is {{ ota_content.json.new_version }}


    - name: Start updating device {{ item }}
      ansible.builtin.uri:
        url: http://{{ item }}/ota?update=true
        body_format: json
        method: POST

    - name: Wait for device {{ item }} to become idle after firmware update
      ansible.builtin.uri:
        url: http://{{ item }}/ota
        body_format: json
        method: POST
        return_content: true
      register: ota_content
      until: ota_content.json.status == "idle"
      retries: 10
      delay: 10
  when: ota_content.json.has_update == true
